### ISSUE TITLE
Not compatible with latest "jit" mode introduced in tailwind

### ISSUE THREAD

**Issue by Tonksthebear** [rodrigore/coc-tailwind-intellisense#11]
Hello! This project no longer seems to be compatible with the latest tailwind version. Tailwind recently added a new jit mode that makes the developer environment drastically better. The official tailwind-intellisense project recently got it working with that mode, so I thought I'd see if this project has any plans to update for compatibility.

Thanks!

**Comment by iofusion** [comment]
This package does work with tailwindcss jit.  Sorry about my previous "thumbs up" on this issue.  Thanks for the time on this tool!!!

**Comment by rodrigore** [comment]
@iofusion hey! thank you for the time to write this.

**Comment by oedotme** [comment]
@rodrigore thanks for your work and time!

I think that the issue @Tonksthebear might have been facing and me as well, that this extension fails to initialize and `coc` stops working too, when `mode` in `tailwind.config.js` is set to `jit`.

It was addressed in [recent release](https://github.com/tailwindlabs/tailwindcss-intellisense/releases/tag/v0.5.10)  of `tailwind-intellisense`.

Thanks!

**Comment by iofusion** [comment]
Whoops, I was mistaken.  Sorry for the misdirection.  

I do not get a complete class listing when `mode: 'jit'` is enabled.  Instead I am seeing classes already in use in the app; it felt complete but wasn't.  Thanks for the clarification @oedotme.
