### ISSUE TITLE
CocUpdate - invalid version

### ISSUE THREAD

**Issue by typicode** [rodrigore/coc-tailwind-intellisense#3]
Hi,

Thanks for the extension.

When running `:CocUpdate`, I'm getting an error:

```
- ✗ coc-tailwind-intellisense Invalid Version: 0.2
```

I think the fix would be to have a version with 3 numbers (e.g. `0.2.1`).

**Comment by rodrigore** [comment]
Hey @typicode  thank you for notice this. 

I just upgrade to 0.3.0 and update to tailwind lsp from 0.4.2 to 0.4.3.

Let me know if is working now.

Thank you again!

**Comment by typicode** [comment]
Yes, thank you :)
