### ISSUE TITLE
Doesn't start when opening file directly from shell

### ISSUE THREAD

**Issue by adriaanzon** [rodrigore/coc-tailwind-intellisense#4]
When opening a file directly from the shell, the language server doesn't start for me. For example when running this:

```sh
nvim index.html
```

I don't get any error; simply nothing happens.

When I open `nvim` first, and then open the file using `:e index.html`, the language server does start normally.

It does work with other language servers, e.g. with phpls (intelephense).

**Comment by seeARMS** [comment]
Having the same issue. Spent a while debugging - nothing in the Coc logs, or anything else to indicate any errors.
