### ISSUE TITLE
Update from latest tailwindcss-intellisense to allow regex

### ISSUE THREAD

**Issue by anark** [rodrigore/coc-tailwind-intellisense#6]
The latest tailwindcss-intellisense allows for setting your own regex so you can use things like twin.macro.

Would it be possible to bring those updates into this COC version?

**Comment by rodrigore** [comment]
Hi!
Can you provided me some example in order to test this new feature?

**Comment by anark** [comment]
Yes,
For example, if you are using the new version of tailwindcss-intellisense and you add the following config
```
"tailwindCSS.colorDecorators": "on",
"tailwindCSS.experimental.classRegex": [
  "tw`([^`]*)", // tw`...`
  "tw=\"([^\"]*)", // <div tw="..." />
  "tw={\"([^\"}]*)", // <div tw={"..."} />
  "tw\\.\\w+`([^`]*)" // tw.xxx`...`
],
"tailwindCSS.includeLanguages": {
  "typescript": "javascript",
  "typescriptreact": "javascript"
}
```

You should get autocompletion on the `...` props labelled `tw="..."` and on template strings `tw\`...\``

**Comment by rodrigore** [comment]
Great, thank you for the snippet.

I'm going to update the server and I will let you know. I just noticed that the creator of the tailwind server change a lot since version 0.4.3, so not sure when I will finish the migration to the last version.

**Comment by anark** [comment]
Sounds good.  The changes are probably due to tailwind 2.0 being released.

**Comment by rodrigore** [comment]
Hey @anark I just updated the server and it seems that the experimental classRegex works fine.
I only update the server implementation, but let me know if something is not working please.

![image](https://user-images.githubusercontent.com/1557305/103162690-69e12880-47d2-11eb-8a97-b9b07ee420e6.png)

![image](https://user-images.githubusercontent.com/1557305/103162693-76fe1780-47d2-11eb-828d-3920fac91592.png)

**Comment by anark** [comment]
Seems to be working fro me!  Thanks so much.
